version: '3.7'
services:

  backend:
    image: proteinevolution/toolkit-docker:latest
    container_name: tk-backend
    environment:
      - SUBMIT_MODE=LOCAL
      - SBT_OPTS=-Xms2G -Xmx4G -Xss2M
    ports:
      - 9000:9000
    # [UP] Uncomment the following three lines for docker-compose up
    # stdin_open: true
    # tty: true
    # command: ["run"]
    volumes:
      - .:/toolkit/backend
      # Uncommenting following 3 lines will speed up sbt boot time significatnly providing you have GeoIP built locally
      - ~/.ivy2:/root/.ivy2
      - ~/.sbt:/root/.sbt
      - ~/.coursier:/root/.coursier
    links:
      - mongodb
    depends_on:
      - mongodb

  frontend:
    image: proteinevolution/toolkit-docker-frontend:latest
    container_name: tk-frontend
    ports:
      - 8080:8080
    # [UP] Uncomment the following three lines for docker-compose up
    # stdin_open: true
    # tty: true
    # command: ["sh","-c", "yarn install && yarn run serve"]
    volumes:
      - ./frontend:/toolkit/frontend

  mongodb:
    image: mongo:4.0
    container_name: tk-mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    ports:
      - 27017:27017
    command: mongod
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
