version: '3.5'
# Here we configure the Containers to run.
services:

  toolkit:
    build: ./project
    container_name: toolkit
    ports:
      - 1234:1234
    links:
      - mongodb
    depends_on:
      - mongodb

  # The container for the MongoDB Database
  mongodb:
    image: mongo:4.0.0
    container_name: tk-mongodb
    environment:
      - MONGO_DATA_DIR=???
      - MONGO_LOG_DIR=???
      - MONGODB_USER=???
      - MONGODB_PASS=???
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config:

# maybe we could also use a docker network if necessary
